# Generated by Django 5.0.7 on 2024-07-21 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerimage',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='photo_viewer.album'),
            preserve_default=False,
        ),
    ]
