# Generated by Django 5.0.7 on 2024-07-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='date_created',
        ),
    ]
