# Generated by Django 5.0.7 on 2024-07-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_viewer', '0002_remove_photographer_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagereference',
            name='id',
        ),
        migrations.AlterField(
            model_name='imagereference',
            name='image_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
