# Generated by Django 5.0.7 on 2024-07-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_viewer', '0002_photographerimage_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerimage',
            name='preview',
            field=models.ImageField(blank=True, upload_to='images/previews/'),
        ),
    ]
